// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2eYFZ2tj3CAy-p-79mRNF2UNDCZiSqHg',
    appId: '1:671876819474:web:abc49ce7c53b12d5fd06cb',
    messagingSenderId: '671876819474',
    projectId: 'rayatrocloth2',
    authDomain: 'rayatrocloth2.firebaseapp.com',
    storageBucket: 'rayatrocloth2.appspot.com',
    measurementId: 'G-H0QS4S19V7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9NYZC5YdOfUB_WzUnJOjDjc9jmk0-OJE',
    appId: '1:671876819474:android:aa621c7d0cf74e04fd06cb',
    messagingSenderId: '671876819474',
    projectId: 'rayatrocloth2',
    storageBucket: 'rayatrocloth2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGjo0AA7YqPhjcVVribNdcgpFXDresskM',
    appId: '1:671876819474:ios:4677203b84b2d908fd06cb',
    messagingSenderId: '671876819474',
    projectId: 'rayatrocloth2',
    storageBucket: 'rayatrocloth2.appspot.com',
    iosClientId: '671876819474-upr4os7fo48hc6vaspnhk41dckbcjpmh.apps.googleusercontent.com',
    iosBundleId: 'com.example.rayatroCloth2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGjo0AA7YqPhjcVVribNdcgpFXDresskM',
    appId: '1:671876819474:ios:4677203b84b2d908fd06cb',
    messagingSenderId: '671876819474',
    projectId: 'rayatrocloth2',
    storageBucket: 'rayatrocloth2.appspot.com',
    iosClientId: '671876819474-upr4os7fo48hc6vaspnhk41dckbcjpmh.apps.googleusercontent.com',
    iosBundleId: 'com.example.rayatroCloth2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2eYFZ2tj3CAy-p-79mRNF2UNDCZiSqHg',
    appId: '1:671876819474:web:b38df91ccc4cedbafd06cb',
    messagingSenderId: '671876819474',
    projectId: 'rayatrocloth2',
    authDomain: 'rayatrocloth2.firebaseapp.com',
    storageBucket: 'rayatrocloth2.appspot.com',
    measurementId: 'G-C11VPT70DC',
  );
}
